
<div id="view-content">
 <h1>Administradores</h1>

<?php $this->mensagem(); ?>

<p>[<a href="<?php echo $this->url(array('action' => 'create')); ?>">novo</a>]</p>

<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Função</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Senha</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($this->usuarios as $usuario) { ?>
        <tr>
          <td><?php echo $usuario['id_usuario']; ?></td>
          <td><?php if ($usuario['funcao'] == '1') { ?>Cozinheiro<?php } else { ?>Gerente<?php } ?></td>
          <td><?php echo $usuario['nome']; ?></td>
          <td><?php echo $usuario['email']; ?></td>
          <td><?php echo $usuario['senha']; ?></td>
          <td>
            [<a href="<?php echo $this->url(array('action' => 'update', 'id_usuario' => $usuario['id_usuario'])); ?>">editar</a>]
            [<a href="<?php echo $this->url(array('action' => 'delete', 'id_usuario' => $usuario['id_usuario'])); ?>">apagar</a>]
          </td>
        </tr>
    <?php } ?>
  </tbody>
</table>
</div>