<?php
if($this->idcategoria !== 0){
    echo $this->headLink()->appendStylesheet('../../../css/bootstrap.min.css');
}else{
    echo $this->headLink()->appendStylesheet('../css/bootstrap.min.css');
}
?>
<h1>Pratos</h1>


<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>Prato</th>
            <th>Categoria</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->prato as $prato) { ?>
            <tr>
                <td><?php echo $prato['descricao']; ?></td>
                <td><?php echo $prato['categoria']; ?></td>
                <td><?php echo $prato['preco']; ?></td>
            </tr>
        <?php } ?>
    </tbody>
