
<div id="view-content">
<h1>Pratos</h1>

<?php $this->mensagem(); ?>

<p>[<a href="<?php echo $this->url(array('action' => 'create')); ?>">novo</a>]</p>

<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Categoria</th>
      <th>Prato</th>
      <th>Preço</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($this->pratos as $prato) { ?>
        <tr>
          <td><?php echo $prato['id_prato']; ?></td>
          <td><?php echo $prato['id_categoria']; ?></td>
          <td><?php echo $prato['descricao']; ?></td>
          <td><?php echo $prato['preco']; ?></td>
          <td>
            <?php  if($this->podeEditar){ ?>[<a href="<?php echo $this->url(array('action' => 'update', 'id_prato' => $prato['id_prato'])); ?>">editar</a>]<?php } ?>
            <?php  if($this->podeApagar){ ?>[<a href="<?php echo $this->url(array('action' => 'delete', 'id_prato' => $prato['id_prato'])); ?>">apagar</a>]<?php } ?>
          </td>
        </tr>
      <?php } ?>
  </tbody>
</table>

</div>