
<div class="page-header">
    <h1>Categorias</h1>
</div>  


<?php $this->mensagem(); ?>

<?php if($this->podeCadastrar){ ?> <p>[<a href="<?php echo $this->url(array('action' => 'create')); ?>">novo</a>]</p><?php }?>

<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Categoria</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->categorias as $categoria) { ?>
            <tr>
                <td><?php echo $categoria['id_categoria']; ?></td>
                <td><?php echo $categoria['categoria']; ?></td>
                <td>
                    <?php if ($this->podeEditar) { ?>[<a href="<?php echo $this->url(array('action' => 'update', 'id_categoria' => $categoria['id_categoria'])); ?>">editar</a>]<?php } ?>
                    <?php if ($this->podeApagar) { ?>[<a href="<?php echo $this->url(array('action' => 'delete', 'id_categoria' => $categoria['id_categoria'])); ?>">apagar</a>]<?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
