<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Zend Framework Quickstart Application</title>
        <?php echo $this->headLink()->appendStylesheet('css/bootstrap.min.css') ?>
    </head>
    <body>
        <div class="container">


            <nav class="navbar navbar-default">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <?php
                            //$this->navigation()->menu()->setPartial('partials/horizontal.phtml');
                            $this->navigation()->menu()->setUlClass('nav navbar-nav');
                            echo $this->navigation()->menu()->render();
                            ?> 
                           
                        </div>
                    </div>
                </div>
            </nav>


            <div class="row">
                <div class="col-xs-12">
                    <ul class="breadcrumb">
                        Você esta em: <?php
                        echo $this->navigation()->breadcrumbs()
                                ->setMinDepth(null) // start at level 0
                                ->setMaxDepth(1) // stop at level 1
                                ->setSeparator('&raquo;');
                        ?>
                    </ul>
                </div>
            </div>
            <?php echo $this->layout()->content ?>
        </div>
    </body>
</html>